#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-bridge","commands":[{"id":"agent-bridge","relativePath":"bin/agent-bridge","purpose":"Communicate with persistent agent sessions"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: 2352d90b7dcf70f9c304dc813f2b786725cf8f26f12d6385d22d73104838fa4b
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-bridge"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-bridge",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-bridge",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Communicate with persistent agent sessions",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-bridge session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
