#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-pull-requests","commands":[{"id":"agent-pull-requests","relativePath":"bin/agent-pull-requests","purpose":"Read and later drive cross-repository pull request state"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: 18f595e1cc8cf7247745298be28acb1e7a77c8a7a2b02b67a30c0473639ebbd1
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-pull-requests"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-pull-requests",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-pull-requests",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Read and later drive cross-repository pull request state",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-pull-requests session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
