#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-ssh","commands":[{"id":"agent-ssh","relativePath":"bin/agent-ssh","purpose":"Emit inspect and verify SSH fabric profiles"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: d4c1d1f596d0a57cfa36857d465d8eedc9db37e175372c7a95a1bebbbe1eda29
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-ssh"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-ssh",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-ssh",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Emit inspect and verify SSH fabric profiles",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-ssh session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
