#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-dispatch","commands":[{"id":"agent-dispatch","relativePath":"bin/agent-dispatch","purpose":"Coordinate queued agent work and task lifecycles"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: cfd9e5e264ca026b7e70140722c45ca997ef3b70bc932a859cd131c34376d791
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-dispatch"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-dispatch",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-dispatch",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Coordinate queued agent work and task lifecycles",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-dispatch session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
