# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-dispatch","commands":[{"id":"agent-dispatch","relativePath":"bin/agent-dispatch","purpose":"Coordinate queued agent work and task lifecycles"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: 6b881d0a5f91a1484d59a3ba26434dff9fab9d0fd7c753ed39ff76ef2237de46
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-dispatch.cmd'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-dispatch'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-dispatch'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Coordinate queued agent work and task lifecycles'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-dispatch session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    'Each `argv` here is a `.cmd` shim: `cmd.exe` ends the command at a newline, so a multi-line argument is silently cut off. Pass multi-line or quote-heavy input through stdin or a file option instead.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
