# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-containers","commands":[{"id":"agent-containers","relativePath":"bin/agent-containers","purpose":"Manage local container fleets leases and dispatch"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 792fba87b764d2f4ce950a3a67a09b99b820d6a1b929ad9034568369b13c973e
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-containers.ps1'
$installerPath = Join-Path $selfRoot 'scripts\init.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-containers'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-containers'
            argv = @($commandPath)
            shell = 'direct'
            purpose = 'Manage local container fleets leases and dispatch'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-containers session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
