# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-vault","commands":[{"id":"agent-vault","relativePath":"bin/agent-vault","purpose":"Fetch and manage machine-local vault credentials"}],"windowsCatalogShim":"cmd"}
# payload-command-catalog-sha256: 297d3566964b5b7a0a280edf75881a4627327fa09b78727efc9fc5b8fcfe5973
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-vault.cmd'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-vault'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-vault'
            argv = @($commandPath)
            shell = 'cmd'
            purpose = 'Fetch and manage machine-local vault credentials'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-vault session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    'Each `argv` here is a `.cmd` shim: `cmd.exe` ends the command at a newline, so a multi-line argument is silently cut off. Pass multi-line or quote-heavy input through stdin or a file option instead.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
