# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-index","commands":[{"id":"agent-index","relativePath":"bin/agent-index","purpose":"Search and operate the semantic index"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 9acd9ab31156b5a06c7219bc4a9ebbc9478e03521b8d0fc510427178d537f0d6
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$catalogGate = Join-Path $selfRoot 'scripts\resolve_effective_config.py'
$python = Get-Command python -ErrorAction SilentlyContinue
if (-not $python) { $python = Get-Command py -ErrorAction SilentlyContinue }
if (-not $python) { Write-Output '{}'; exit 0 }
& $python.Source -E -X utf8 $catalogGate --check --cwd (Get-Location).Path *> $null
if ($LASTEXITCODE -ne 0) { Write-Output '{}'; exit 0 }

$commandPath = Join-Path $selfRoot 'bin\agent-index.ps1'
$installerPath = Join-Path $selfRoot 'scripts\install.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-index'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-index'
            argv = @($commandPath)
            shell = 'direct'
            purpose = 'Search and operate the semantic index'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-index session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
