#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-index","commands":[{"id":"agent-index","relativePath":"bin/agent-index","purpose":"Search and operate the semantic index"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 1fe2a1ca202d78df80a1dbfcb4eef62232e7bdb28a38497d80876db7a11414c3
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-index"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}
catalog_gate="$self_root/scripts/resolve_effective_config.py"
if ! "$py" -E -X utf8 "$catalog_gate" --check --cwd "$PWD"; then
    printf '%s\n' '{}'
    exit 0
fi

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-index",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-index",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Search and operate the semantic index",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-index session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
