#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"budget-guidance","commands":[{"id":"budget-guidance","relativePath":"bin/budget-guidance","purpose":"Report current attributable budget posture"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: b2970f1b8407f379dde83a68949a3a2243ba9e0fc7b1d5f40f927e39cb3fd318
set -eu

json_escape() {
    local value="$1"
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//$'\r'/\\r}"
    value="${value//$'\n'/\\n}"
    value="${value//$'\t'/\\t}"
    printf '%s' "$value"
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/budget-guidance"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"

catalog="{\"schema\":\"copilot-extensions.session-command-catalog\",\"version\":1,\"plugin\":\"budget-guidance\",\"payload\":{\"provenance\":\"payload-local\"},\"commands\":[{\"id\":\"budget-guidance\",\"argv\":[\"$(json_escape "$command_path")\"],\"shell\":\"direct\",\"purpose\":\"Report current attributable budget posture\",\"availability\":\"$availability\"}]}"
context="## budget-guidance session command catalog

Invoke the exact \`argv\` below. Do not search \`PATH\` or substitute a same-named command from another payload.

\`\`\`json
$catalog
\`\`\`"
printf '{"additionalContext":"%s"}\n' "$(json_escape "$context")"
