#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-logger","commands":[{"id":"agent-logger","relativePath":"bin/agent-logger","purpose":"Inspect agent logger configuration and chronicle state"},{"id":"collate-session","relativePath":"bin/collate-session","purpose":"Collate one Copilot session into digest segments"},{"id":"read-session-digest","relativePath":"bin/read-session-digest","purpose":"Read collated session digest data"},{"id":"prepare-session-log","relativePath":"bin/prepare-session-log","purpose":"Prepare one session log manifest and output path"},{"id":"ramp-up-session","relativePath":"bin/ramp-up-session","purpose":"Build a bounded takeover briefing for a dormant session"},{"id":"session-sync","relativePath":"bin/session-sync","purpose":"Sync archive and compact Copilot session data"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: e926e607ef638cba72d8575b67e1b9bff05c1f816400ef0073084c447d7a368e
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

installer_path="$self_root/scripts/install.sh"
command_specs='[{"id":"agent-logger","relativePath":"bin/agent-logger","purpose":"Inspect agent logger configuration and chronicle state"},{"id":"collate-session","relativePath":"bin/collate-session","purpose":"Collate one Copilot session into digest segments"},{"id":"read-session-digest","relativePath":"bin/read-session-digest","purpose":"Read collated session digest data"},{"id":"prepare-session-log","relativePath":"bin/prepare-session-log","purpose":"Prepare one session log manifest and output path"},{"id":"ramp-up-session","relativePath":"bin/ramp-up-session","purpose":"Build a bounded takeover briefing for a dormant session"},{"id":"session-sync","relativePath":"bin/session-sync","purpose":"Sync archive and compact Copilot session data"}]'
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(SELF_ROOT="$self_root" INSTALLER_PATH="$installer_path" COMMAND_SPECS="$command_specs" "$py" <<'PY'
import json
import os

installer_ready = os.path.isfile(os.environ["INSTALLER_PATH"])
commands = []
for spec in json.loads(os.environ["COMMAND_SPECS"]):
    command_path = os.path.join(
        os.environ["SELF_ROOT"], *spec["relativePath"].split("/")
    )
    commands.append(
        {
            "id": spec["id"],
            "argv": [command_path],
            "shell": "direct",
            "purpose": spec["purpose"],
            "availability": (
                "ready"
                if installer_ready
                and os.path.isfile(command_path)
                and os.access(command_path, os.X_OK)
                else "unavailable"
            ),
        }
    )

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-logger",
    "payload": {"provenance": "payload-local"},
    "commands": commands,
}
context = (
    "## agent-logger session command catalog\n\n"
    "Select the command by `id` and invoke its exact `argv`. "
    "Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
