#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-machines","commands":[{"id":"agent-machines","relativePath":"bin/agent-machines","purpose":"Discover validate and restore declared machine state"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 127b61f14fffcb2e0fa254eb909038f61d24ea379bfc1a89fbda1fcaa28b78bd
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-machines"
installer_path="$self_root/scripts/init.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-machines",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-machines",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Discover validate and restore declared machine state",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-machines session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
