# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-machines","commands":[{"id":"agent-machines","relativePath":"bin/agent-machines","purpose":"Discover validate and restore declared machine state"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 5fcd22f2413d0ac3376aa6b8521ee1b066d688ed233e76db15287a830b8f12ed
$ErrorActionPreference = 'SilentlyContinue'

$selfRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path

$commandPath = Join-Path $selfRoot 'bin\agent-machines.ps1'
$installerPath = Join-Path $selfRoot 'scripts\init.ps1'
$availability = if (
    (Test-Path -LiteralPath $commandPath) -and
    (Test-Path -LiteralPath $installerPath)
) { 'ready' } else { 'unavailable' }
$catalog = [ordered]@{
    schema = 'copilot-extensions.session-command-catalog'
    version = 1
    plugin = 'agent-machines'
    payload = [ordered]@{ provenance = 'payload-local' }
    commands = @(
        [ordered]@{
            id = 'agent-machines'
            argv = @($commandPath)
            shell = 'direct'
            purpose = 'Discover validate and restore declared machine state'
            availability = $availability
        }
    )
}
$catalogJson = $catalog | ConvertTo-Json -Compress -Depth 6
$fence = '```'
$context = @(
    '## agent-machines session command catalog'
    ''
    'Invoke the exact `argv` below. Do not search `PATH` or substitute a same-named command from another payload.'
    ''
    "${fence}json"
    $catalogJson
    $fence
) -join "`n"
Write-Output (@{ additionalContext = $context } | ConvertTo-Json -Compress -Depth 3)
exit 0
