"""Regression guard: the Windows coordinator/supervisor launcher generators
must prefer last-known-good over a raw newest-slot guess when the
current-version marker is missing/stale (#742) -- matching the canonical
resolve-runtime.ps1 chain, so a call during a brief mid-swap window can't
bind a still-installing or never-activated slot.
"""

from __future__ import annotations

from pathlib import Path

_PLUGIN_ROOT = Path(__file__).resolve().parents[1]
_INSTALL_PS1 = _PLUGIN_ROOT / "scripts" / "install.ps1"


def _text() -> str:
    return _INSTALL_PS1.read_text(encoding="utf-8")


def _assert_lkg_before_guess(text: str, start: int, end: int) -> None:
    block = text[start:end]
    marker_idx = block.index("current-version")
    guess_idx = block.index("Sort-Object Name")
    lkg_idx = block.index("last-known-good")
    assert marker_idx < lkg_idx < guess_idx, (
        "last-known-good must be consulted after the current-version marker "
        "but strictly before the newest-slot guess"
    )


def test_coordinator_launcher_tries_last_known_good_before_newest_slot_guess():
    text = _text()
    start = text.index("# agent-dispatch coordinator launcher (generated by install.ps1")
    end = text.index("# agent-dispatch embody supervisor launcher (generated by install.ps1")
    _assert_lkg_before_guess(text, start, end)


def test_supervisor_launcher_tries_last_known_good_before_newest_slot_guess():
    text = _text()
    start = text.index("# agent-dispatch embody supervisor launcher (generated by install.ps1")
    _assert_lkg_before_guess(text, start, len(text))
