#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-codespaces","commands":[{"id":"agent-codespaces","relativePath":"bin/agent-codespaces","purpose":"Manage GitHub Codespaces lifecycle transport and dispatch"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 4f70b9c5d0f3bf162993fb16f11b13109ca560384d7e7ad3d07796b0c9b61726
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/agent-codespaces"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-codespaces",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-codespaces",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Manage GitHub Codespaces lifecycle transport and dispatch",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-codespaces session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
