#!/usr/bin/env bash
# Generated by libs/payload-invocation/generate.py. Do not edit.
# payload-command-catalog-contract: {"plugin":"agent-worktrees","commands":[{"id":"agent-worktrees","relativePath":"bin/payload/agent-worktrees","purpose":"Manage worktrees and project lifecycle"}],"windowsCatalogShim":"powershell"}
# payload-command-catalog-sha256: 49a65b497af1b6eb87011c950733e493ed8a1fd074e85c2ce70257ddaa5946ac
set -eu

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
self_root="$(cd "$script_dir/.." && pwd -P)"

command_path="$self_root/bin/payload/agent-worktrees"
installer_path="$self_root/scripts/install.sh"
availability="unavailable"
[ -x "$command_path" ] && [ -f "$installer_path" ] && availability="ready"
py="$(command -v python3 || command -v python || true)"
[ -n "$py" ] || {
    printf '%s\n' '{}'
    exit 0
}

if output="$(COMMAND_PATH="$command_path" AVAILABILITY="$availability" "$py" <<'PY'
import json
import os

catalog = {
    "schema": "copilot-extensions.session-command-catalog",
    "version": 1,
    "plugin": "agent-worktrees",
    "payload": {"provenance": "payload-local"},
    "commands": [
        {
            "id": "agent-worktrees",
            "argv": [os.environ["COMMAND_PATH"]],
            "shell": "direct",
            "purpose": "Manage worktrees and project lifecycle",
            "availability": os.environ["AVAILABILITY"],
        }
    ],
}
context = (
    "## agent-worktrees session command catalog\n\n"
    "Invoke the exact `argv` below. Do not search `PATH` or substitute a "
    "same-named command from another payload.\n\n"
    "```json\n"
    + json.dumps(catalog, sort_keys=True)
    + "\n```"
)
print(json.dumps({"additionalContext": context}))
PY
)"; then
    printf '%s\n' "$output"
else
    printf '%s\n' '{}'
fi
